FROM node:23-slim

WORKDIR /app

RUN apt-get update && apt-get install -y wget

RUN npm install -g @ionic/cli

COPY package.json package-lock.json* ./
RUN npm ci

COPY . .

EXPOSE 8100

CMD ["ionic", "serve", "--host=0.0.0.0", "--livereload"]