FROM node:23-slim

WORKDIR /app

RUN apt-get update && apt-get install -y wget

RUN npm install -g @ionic/cli

COPY package.json package-lock.json* ./
RUN npm ci

COPY . .
COPY start.sh /app/start.sh
RUN chmod +x /app/start.sh

EXPOSE 8100

CMD ["/app/start.sh"]