FROM node:23-slim

WORKDIR /app

RUN apt-get update && apt-get install -y wget dos2unix

RUN npm install -g @ionic/cli

COPY package.json package-lock.json* ./
RUN npm ci

COPY . .
# Convertir les fins de ligne Windows en Unix et rendre le script exécutable
RUN dos2unix /app/start.sh && chmod +x /app/start.sh

EXPOSE 8100

CMD ["/bin/bash", "/app/start.sh"]